const translations={
kk:{skip:"Мазмұнға өту",navResources:"Ресурстар",navAbout:"Генеративті жасанды интеллект туралы",eyebrow:"Жоғары білімге арналған",heroTitle:"Генеративті жасанды интеллект үшін қажеттінің бәрі — бір жерде",heroText:"Оқытуды, зерттеуді және университет жұмысын жақсартуға арналған практикалық AI ресурстары.",heroCta:"Ресурстарды ашу",libraryKicker:"Ресурстар кітапханасы",libraryTitle:"Қажетті бағытты таңдаңыз",adminTitle:"Әкімшілік және университеттік операциялар",productivityTitle:"Кәсіби өнімділік және даму",researchTitle:"Зерттеу және инновация",teachingTitle:"Оқыту, оқу және оқу бағдарламасы",adminDesc:"Университетті басқару және әкімшілік процестер.",productivityDesc:"Кәсіби тиімділік пен үздіксіз даму құралдары.",researchDesc:"Ғылыми зерттеу мен инновацияға арналған ресурстар.",teachingDesc:"Оқыту, оқу және оқу бағдарламасын дамыту.",aboutKicker:"Генеративті жасанды интеллект туралы",aboutTitle:"Білім беру қауымдастығына арналған қауіпсіз AI кеңістігі",aboutText:"Генеративті жасанды интеллект — университеттерге AI-ды оқытуда, зерттеуде және күнделікті жұмыста жауапкершілікпен қолдануға көмектесетін білім беру шешімі.",aboutCta:"Толығырақ білу",back:"← Басты бетке оралу",categoryDescriptions:{administration:"Университет операцияларын, құжаттарды және әкімшілік жұмыс процестерін жақсартуға арналған Генеративті жасанды интеллект ресурстары.",productivity:"Күнделікті жұмысты тиімді ұйымдастыруға, дағдыларды дамытуға және кәсіби өсуге арналған ресурстар.",research:"Ғылыми идеядан нәтижеге дейінгі зерттеу мен инновация процесін қолдайтын ресурстар.",teaching:"Сабақ жоспарлау, оқыту, бағалау және оқу бағдарламасын жетілдіруге арналған ресурстар."},resourceLibraryTitle:"Ресурстар кітапханасы",resourceNames:["Промпт банкі","Промпт модельдері","PDF гайдтар мен кітапшалар","Алдын ала жазылған тренингтер","AI қауіпсіздік тексеру тізімі","Дейін / Кейін кейстері","Шығармашылық қолдану мысалдары"]},
ru:{skip:"Перейти к содержанию",navResources:"Ресурсы",navAbout:"О генеративном искусственном интеллекте",eyebrow:"Для высшего образования",heroTitle:"Всё необходимое для генеративного искусственного интеллекта — в одном месте",heroText:"Практические AI-ресурсы для преподавания, исследований и университетской работы.",heroCta:"Открыть ресурсы",libraryKicker:"Библиотека ресурсов",libraryTitle:"Выберите нужное направление",adminTitle:"Администрирование и университетские операции",productivityTitle:"Профессиональная продуктивность и развитие",researchTitle:"Исследования и инновации",teachingTitle:"Преподавание, обучение и учебная программа",adminDesc:"Управление университетом и административные процессы.",productivityDesc:"Инструменты профессиональной эффективности и развития.",researchDesc:"Ресурсы для научных исследований и инноваций.",teachingDesc:"Преподавание, обучение и развитие учебных программ.",aboutKicker:"О генеративном искусственном интеллекте",aboutTitle:"Безопасное AI-пространство для образовательного сообщества",aboutText:"Генеративный искусственный интеллект — образовательное решение, которое помогает университетам ответственно применять AI в преподавании, исследованиях и повседневной работе.",aboutCta:"Узнать больше",back:"← Вернуться на главную",categoryDescriptions:{administration:"Ресурсы по генеративному искусственному интеллекту для совершенствования университетских операций, документов и административных процессов.",productivity:"Ресурсы для эффективной организации работы, развития навыков и профессионального роста.",research:"Ресурсы для поддержки исследований и инноваций на всём пути — от научной идеи до результата.",teaching:"Ресурсы для планирования занятий, преподавания, оценивания и развития учебных программ."},resourceLibraryTitle:"Библиотека ресурсов",resourceNames:["Банк промптов","Модели промптов","PDF-гайды и пособия","Записанные тренинги","Чек-лист безопасности AI","Кейсы До / После","Примеры творческого применения"]},
en:{skip:"Skip to content",navResources:"Resources",navAbout:"About generative artificial intelligence",eyebrow:"Built for higher education",heroTitle:"Everything for generative artificial intelligence in one place",heroText:"Practical AI resources for teaching, research, and university operations.",heroCta:"Explore resources",libraryKicker:"Resource library",libraryTitle:"Choose your focus",adminTitle:"Administration and University Operations",productivityTitle:"Professional Productivity and Development",researchTitle:"Research and Innovation",teachingTitle:"Teaching, Learning, and Curriculum",adminDesc:"University management and administrative workflows.",productivityDesc:"Tools for professional productivity and continuous development.",researchDesc:"Resources for scientific research and innovation.",teachingDesc:"Teaching, learning, and curriculum development.",aboutKicker:"About generative artificial intelligence",aboutTitle:"A secure AI workspace for the education community",aboutText:"generative artificial intelligence is an education-focused solution that helps universities use AI responsibly across teaching, research, and everyday work.",aboutCta:"Learn more",back:"← Back to home",categoryDescriptions:{administration:"generative artificial intelligence resources for improving university operations, documents, and administrative workflows.",productivity:"Resources for organizing work, developing skills, and supporting professional growth.",research:"Resources that support research and innovation from the first idea through to results.",teaching:"Resources for lesson planning, teaching, assessment, and curriculum development."},resourceLibraryTitle:"Resource Library",resourceNames:["Prompt Bank","Prompt Models","PDF Guides & Handbooks","Pre-recorded Trainings","AI Safety Checklist","Before / After Cases","Creative Use Examples"]}
};
translations.kk.eyebrow="Жоғары білім және ғылымға арналған";
translations.kk.heroTitle="Генеративті жасанды интеллект үшін қажеттінің бәрі — бір жерде";
translations.ru.eyebrow="Для высшего образования и науки";
translations.ru.heroTitle="Всё необходимое для генеративного искусственного интеллекта — в одном месте";
translations.en.eyebrow="For higher education and research";
translations.en.heroTitle="Everything for generative artificial intelligence — in one place";
translations.kk.productivityTitle="ЖҰМЫС ПРОЦЕСІ ҮШІН AI";
translations.kk.researchTitle="ЗЕРТТЕУ ПРОЦЕСІ ҮШІН AI";
translations.kk.productivityDesc="Күнделікті жұмысты жоспарлау мен орындауға арналған AI құралдары.";
translations.kk.researchDesc="Ғылыми идеядан нәтижеге дейінгі зерттеу процесіне арналған ресурстар.";
translations.kk.resourceNames[0]="Промпт конструктор";
translations.ru.productivityTitle="AI ДЛЯ РАБОЧЕГО ПРОЦЕССА";
translations.ru.researchTitle="AI ДЛЯ ИССЛЕДОВАТЕЛЬСКОГО ПРОЦЕССА";
translations.ru.productivityDesc="AI-инструменты для планирования и выполнения повседневной работы.";
translations.ru.researchDesc="Ресурсы для исследовательского процесса — от научной идеи до результата.";
translations.ru.resourceNames[0]="Конструктор промптов";
translations.en.productivityTitle="AI FOR WORKFLOWS";
translations.en.researchTitle="AI FOR RESEARCH";
translations.en.productivityDesc="AI tools for planning and completing everyday work.";
translations.en.researchDesc="Resources for the research process, from the first idea through to results.";
translations.en.resourceNames[0]="Prompt Builder";
Object.assign(translations.kk,{brandName:"Академиялық AI ассистент",eyebrow:"Академиялық жұмыстың жаңа тәсілі",heroTitle:"Докторанттар мен оқытушыларға арналған AI көмекшісі.",heroText:"Зерттеу өнімділігін арттырыңыз: AI-ды тиімді, жауапты және этикалық қолдануға арналған нақты промпттарды бірнеше қадамда құрастырыңыз.",heroCta:"ПРОМПТ КОНСТРУКТОР",portalKicker:"БІР МАҚСАТ · БІР ДӘЛ ПРОМПТ",portalStep1:"Бағыт",portalStep2:"Контекст",portalStep3:"Нәтиже"});
Object.assign(translations.ru,{brandName:"Академиялық AI ассистент",eyebrow:"Новый подход к академической работе",heroTitle:"AI-помощник для докторантов и преподавателей.",heroText:"Повысьте исследовательскую продуктивность: создавайте точные промпты для эффективного, ответственного и этичного использования AI.",heroCta:"КОНСТРУКТОР ПРОМПТОВ",portalKicker:"ОДНА ЦЕЛЬ · ОДИН ТОЧНЫЙ ПРОМПТ",portalStep1:"Направление",portalStep2:"Контекст",portalStep3:"Результат"});
Object.assign(translations.en,{brandName:"Академиялық AI ассистент",eyebrow:"A new way to do academic work",heroTitle:"An AI assistant for doctoral researchers and educators.",heroText:"Boost research productivity by creating precise prompts for effective, responsible, and ethical AI use.",heroCta:"PROMPT BUILDER",portalKicker:"ONE GOAL · ONE PRECISE PROMPT",portalStep1:"Direction",portalStep2:"Context",portalStep3:"Result"});
Object.assign(translations.kk,{communityKicker:"ЗЕРТТЕУШІЛЕР ҚАУЫМДАСТЫҒЫ",communityTitle:"Пайдалы академиялық ортаға қосылыңыз",communityText:"Telegram арнасы мен WhatsApp тобындағы пайдалы материалдарды алыңыз және жоба авторымен танысыңыз.",communityCta:"АВТОР ЖӘНЕ ҚАУЫМДАСТЫҚ",authorRole:"AI-методолог · зерттеуші · оқытушы",authorAbout:"АВТОР ТУРАЛЫ",telegramLabel:"Зерттеуші Қазақстан арнасы",whatsappLabel:"Пайдалы ақпарат тобы",authorBioTitle:"Кәсіби және академиялық тәжірибе",authorBio:`AI-методолог. «Болашақ» халықаралық стипендиясының түлегі. 2014 жылы Ұлыбританиядағы Рединг университетінің Pre-sessional Academic English курсын тәмамдаған. 2015 жылы Лидс университетінде Academic English for Postgraduate Studies курсын аяқтаған. 2016 жылы Суррей университетінде «Халықаралық туризм менеджменті» мамандығы бойынша ғылым магистрі (MSc) дәрежесін иеленген. 2016 жылдан бері Нархоз университеті, UİB және IUTH секілді жоғары оқу орындарында ғылыми-зерттеу және аға оқытушылық қызмет атқарған. Alanya Alaaddin Keykubat University университетінің PhD докторанты. 2023 жылы ҚР Президенті жанындағы Қазақстан стратегиялық зерттеулер институтының «Қазақстан: дамудың сын-қатерлері мен шешу жолдары» атты екінші Жас сарапшыларды қолдау бағдарламасының финалист-жеңімпазы. Scopus және КОКСОН журналдарындағы бірнеше мақаланың, туризм саласына қатысты монографиялардың авторы. 2023–2025 жылдарға арналған ғылыми және ғылыми-техникалық жобалар бойынша гранттық қаржыландыру конкурсында әлеуметтік және гуманитарлық ғылымдар бағыты бойынша 70 млн теңге грант иегері.`});
Object.assign(translations.ru,{communityKicker:"СООБЩЕСТВО ИССЛЕДОВАТЕЛЕЙ",communityTitle:"Присоединяйтесь к полезной академической среде",communityText:"Получайте полезные материалы в Telegram-канале и WhatsApp-группе и познакомьтесь с автором проекта.",communityCta:"АВТОР И СООБЩЕСТВО",authorRole:"AI-методолог · исследователь · преподаватель",authorAbout:"ОБ АВТОРЕ",telegramLabel:"Канал «Зерттеуші Қазақстан»",whatsappLabel:"Группа полезной информации",authorBioTitle:"Профессиональный и академический опыт",authorBio:`AI-методолог, выпускник международной стипендии «Болашақ». В 2014 году окончил курс Pre-sessional Academic English в Университете Рединга, Великобритания. В 2015 году завершил курс Academic English for Postgraduate Studies в Университете Лидса. В 2016 году получил степень магистра наук (MSc) по специальности «Международный туристический менеджмент» в Университете Суррея. С 2016 года занимался научно-исследовательской и преподавательской деятельностью в Университете Нархоз, UİB и IUTH. PhD-докторант Alanya Alaaddin Keykubat University. В 2023 году стал финалистом-победителем второй программы поддержки молодых экспертов Казахстанского института стратегических исследований при Президенте РК «Казахстан: вызовы развития и пути решения». Автор нескольких статей в журналах Scopus и КОКСОН, а также монографий в сфере туризма. Обладатель гранта в размере 70 млн тенге по направлению социальных и гуманитарных наук в конкурсе грантового финансирования научных и научно-технических проектов на 2023–2025 годы.`});
Object.assign(translations.en,{communityKicker:"RESEARCHER COMMUNITY",communityTitle:"Join a practical academic community",communityText:"Access useful materials through the Telegram channel and WhatsApp group, and meet the project author.",communityCta:"AUTHOR AND COMMUNITY",authorRole:"AI methodologist · researcher · educator",authorAbout:"ABOUT THE AUTHOR",telegramLabel:"Zertteushi Qazaqstan channel",whatsappLabel:"Useful information group",authorBioTitle:"Professional and academic experience",authorBio:`AI methodologist and alumnus of the Bolashak International Scholarship. In 2014, he completed the Pre-sessional Academic English course at the University of Reading, United Kingdom. In 2015, he completed Academic English for Postgraduate Studies at the University of Leeds. In 2016, he earned an MSc in International Tourism Management from the University of Surrey. Since 2016, he has held research and senior teaching roles at universities including Narxoz University, UİB and IUTH. He is a PhD candidate at Alanya Alaaddin Keykubat University. In 2023, he became a finalist and winner of the second Young Experts Support Programme, “Kazakhstan: Development Challenges and Solutions,” organized by the Kazakhstan Institute for Strategic Studies under the President of the Republic of Kazakhstan. He is the author of several articles in Scopus and КОКСОН journals and monographs related to tourism. He received a KZT 70 million grant in the social sciences and humanities track of the 2023–2025 competition for grant funding of scientific and scientific-technical projects.`});
const categoryKeys={administration:"adminTitle",productivity:"productivityTitle",research:"researchTitle",teaching:"teachingTitle"};
const resourceIcons=["⌘","◇","↓","▶","✓","⇄","✦"];
function renderResourceLibrary(t){const title=document.querySelector("[data-category-library-title]");if(title)title.textContent=t.resourceLibraryTitle;const grid=document.querySelector("[data-category-resource-grid]");if(!grid)return;const category=document.body.dataset.category;const isResearch=category==="research";const isProductivity=category==="productivity";const isTeaching=category==="teaching";const researchLinks=["research-prompts.html","prompt-models.html","pdf-guides.html","research-trainings.html","ai-safety-checklist.html","before-after-cases.html","creative-ai-lab.html"];const productivityLinks=["productivity-prompts.html","productivity-models.html","productivity-guides.html","productivity-trainings.html","productivity-safety.html","productivity-cases.html","productivity-creative.html"];const teachingLinks=["teaching-prompts.html",null,null,null,null,null,null];const resourceIndexes=isResearch?[0,2,3]:t.resourceNames.map((_,index)=>index);grid.innerHTML=resourceIndexes.map(index=>{const name=t.resourceNames[index];const creativeName={kk:"Креатив қолдану мысалдары",ru:"Креативные примеры использования",en:"Creative Use Examples"};const safetyName={kk:"AI қауіпсіздік чеклисті",ru:"Чек-лист безопасности AI",en:"AI Safety Checklist"};const localized=document.documentElement.lang;const displayName=(isResearch||isProductivity)&&index===6?(creativeName[localized]||creativeName.kk):(isResearch||isProductivity)&&index===4?(safetyName[localized]||safetyName.kk):name;const content=`<span class="library-icon" aria-hidden="true">${resourceIcons[index]}</span><span><small>${String(index+1).padStart(2,"0")}</small><strong>${displayName}</strong></span><i aria-hidden="true">↗</i>`;const href=isResearch?researchLinks[index]:isProductivity?productivityLinks[index]:isTeaching?teachingLinks[index]:null;const classes=["library-button"];if(isResearch&&index===0)classes.push("library-button--primary");if(!isResearch&&index===6)classes.push("library-button--wide");return href?`<a class="${classes.join(" ")}" href="${href}">${content}</a>`:`<button class="${classes.join(" ")}" type="button">${content}</button>`}).join("")}
function setLanguage(lang){const t=translations[lang]||translations.kk;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=t[el.dataset.i18n];if(typeof value==="string")el.textContent=value});const category=document.body.dataset.category;if(category){const title=t[categoryKeys[category]];document.querySelector("[data-category-title]").textContent=title;document.querySelector("[data-category-description]").textContent=t.categoryDescriptions[category];document.title=`${title} — AI for Research Central Asia`;renderResourceLibrary(t)}localStorage.setItem("ai-academy-language",lang)}
const select=document.querySelector("#language-select"),saved=localStorage.getItem("ai-academy-language")||"kk";if(select){select.value=saved;select.addEventListener("change",event=>setLanguage(event.target.value))}setLanguage(saved);
const authorDialog=document.querySelector("#author-dialog"),authorOpen=document.querySelector("#author-open"),authorClose=document.querySelector("#author-close");
if(authorDialog&&authorOpen&&authorClose){authorOpen.addEventListener("click",()=>{if(typeof authorDialog.showModal==="function")authorDialog.showModal();else authorDialog.setAttribute("open","")});authorClose.addEventListener("click",()=>authorDialog.close());authorDialog.addEventListener("click",event=>{if(event.target===authorDialog)authorDialog.close()})}
